### ISSUE TITLE
Suggestion: Add binder example

### ISSUE THREAD

**Issue by trallard** [AnyBody-Research-Group/AnyPyTools#57]
Hi! Not a blocker or essential for the JOSS submission, but since this package is intended for reproducible science and you already have a set of Jupyter notebooks as a tutorial I think it would be awesome to use binder for this. 

It would help folks to follow the tutorial using an interactive environment.
If you would like to discuss or need some help feel free to ping me

**Comment by melund** [comment]
Thanks, @trallard. Binder is awesome and I did look into it when I created the notebook tutorial. To be useful the binder environment would have to include the AnyBody Modeling System. It wasn't possible back then. 

It looks like a lot has happened since. The possibility of using docker images is new to me and promising. 

The problem is the Windows dependency imposed by the AnyBody Modeling System. Maybe Windows docker containers could be used, but that is not supported by Binder.

**Comment by trallard** [comment]
Ahhhhh I did not see that Windows dependency :( I will check if there is a way around it and report back.
The beauty of binder is that you do not need to create your own containers or have a deep understanding of them to use it as it is all taken care of with `repo2docker` under the hood
